"""empty message

Revision ID: 39badc5fbd0e
Revises: c051fc3c27c4
Create Date: 2024-05-30 12:00:54.142670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39badc5fbd0e'
down_revision = 'c051fc3c27c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
