"""empty message

Revision ID: 67fbae8c969a
Revises: f0e743ae1ca8
Create Date: 2024-05-10 15:38:15.658202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fbae8c969a'
down_revision = 'f0e743ae1ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint('pet_race_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_unique_constraint('pet_race_key', ['race'])

    # ### end Alembic commands ###
