"""empty message

Revision ID: 95893bde0b78
Revises: 7beaedd2b4b3
Create Date: 2024-05-27 10:12:21.618159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95893bde0b78'
down_revision = '7beaedd2b4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
